# Generated by Django 5.0.4 on 2024-04-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='TaskGroup',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='group',
            new_name='taskGroup',
        ),
    ]
